<?php
if (session_status() === PHP_SESSION_NONE) session_start();
include '../../../db_connect.php';
include '../../../includes/admin_header.php';
include '../../../includes/auth_check.php';
requireRole(['Admin']);

if (empty($_SESSION['_csrf'])) {
    $_SESSION['_csrf'] = bin2hex(random_bytes(32));
}
$csrf = $_SESSION['_csrf'];

// ==================== 🧠 1️⃣ TỰ ĐỘNG TẠO & CẬP NHẬT HÓA ĐƠN ====================

// Hàm kiểm tra cột tồn tại
// Hàm kiểm tra cột tồn tại (Robust version)
function addColumnIfNotExists($conn, $table, $column, $definition) {
    // 1. Check if table exists
    $tableCheck = $conn->query("SHOW TABLES LIKE '$table'");
    if (!$tableCheck || $tableCheck->num_rows == 0) return;

    // 2. Check if column exists using SHOW COLUMNS (More reliable than INFO_SCHEMA in some envs)
    $colCheck = $conn->query("SHOW COLUMNS FROM `$table` LIKE '$column'");
    
    if ($colCheck && $colCheck->num_rows == 0) {
        // Column doesn't exist, allow add
        $conn->query("ALTER TABLE `$table` ADD COLUMN `$column` $definition");
    }
}

// 🔹 Thêm các cột nếu chưa có (CHẠY TRƯỚC KHI UPDATE)
addColumnIfNotExists($conn, "Invoices", "DueDate", "DATE NULL AFTER CreatedAt");
addColumnIfNotExists($conn, "Invoices", "Note", "NVARCHAR(255) NULL AFTER TotalAmount");
addColumnIfNotExists($conn, "Invoices", "PaidAt", "DATETIME NULL AFTER DueDate");

// --- 1. Tự động set DueDate = CreatedAt + 5 ngày cho hóa đơn chưa có hạn ---
$conn->query("
    UPDATE Invoices 
    SET DueDate = DATE_ADD(CreatedAt, INTERVAL 5 DAY)
    WHERE DueDate IS NULL
");

// --- 2. Cập nhật trạng thái 'Đã thanh toán' nếu đã có PaidAt ---
$conn->query("
    UPDATE Invoices
    SET Status = 'Đã thanh toán'
    WHERE PaidAt IS NOT NULL
      AND (Status IS NULL OR Status <> 'Đã thanh toán')
");

// --- 3. Cập nhật trạng thái 'Quá hạn' cho hóa đơn chưa thanh toán, quá hạn ---
$conn->query("
    UPDATE Invoices 
    SET Status = 'Quá hạn'
    WHERE PaidAt IS NULL
      AND Status = 'Chưa thanh toán'
      AND DueDate IS NOT NULL
      AND DueDate < CURDATE()
");

// 🔔 Gửi thông báo cho sinh viên có hóa đơn quá hạn
$overdueInvoices = $conn->query("
    SELECT i.InvoiceID, i.ContractID, i.Month, i.Year, s.StudentID, s.UserID, s.FullName, s.Email, r.RoomNumber
    FROM Invoices i
    JOIN Contracts c ON i.ContractID = c.ContractID
    JOIN Students s ON c.StudentID = s.StudentID
    JOIN Rooms r ON c.RoomID = r.RoomID
    WHERE i.Status = 'Quá hạn'
      AND i.DueDate < CURDATE()
      AND NOT EXISTS (
          SELECT 1 FROM Notifications n 
          WHERE n.UserID = s.UserID
            AND n.Title = CONCAT('Hóa đơn tháng ', i.Month, '/', i.Year, ' bị quá hạn')
      )
");

while ($inv = $overdueInvoices->fetch_assoc()) {
    $studentID = $inv['StudentID'];
    $month = $inv['Month'];
    $year = $inv['Year'];
    $room = $inv['RoomNumber'];
    $title = "Hóa đơn tháng $month/$year bị quá hạn";
    $message = "Xin chào {$inv['FullName']},<br>
        Hóa đơn phòng <strong>$room</strong> tháng <strong>$month/$year</strong> đã <span style='color:red;'>quá hạn thanh toán</span>.<br>
        Vui lòng thanh toán sớm nhất để tránh bị xử lý theo quy định.<br><br>
        — Hệ thống Ký túc xá";

    // ✅ Lưu thông báo vào database
    // ✅ Lưu thông báo vào database
    $userID = $inv['UserID'];
    if ($userID) {
        $stmt = $conn->prepare("INSERT INTO Notifications (UserID, Title, Message) VALUES (?, ?, ?)");
        $stmt->bind_param("iss", $userID, $title, $message);
        $stmt->execute();
    }

    // ✅ Gửi email (nếu có địa chỉ email sinh viên)
    if (!empty($inv['Email'])) {
        @mail(
            $inv['Email'],
            "🔔 Thông báo hóa đơn quá hạn | Ký túc xá",
            strip_tags($message), // bỏ HTML
            "From: no-reply@ktx-system.local\r\nContent-Type: text/plain; charset=UTF-8"
        );
    }
}


// 🔹 Tự động tạo hóa đơn hàng tháng cho hợp đồng hiệu lực
$autoGenerated = $conn->query("
    INSERT INTO Invoices (ContractID, Month, Year, RoomFee, ElectricUsage, ElectricPrice, WaterUsage, WaterPrice, TotalAmount, Status, CreatedAt, DueDate)
    SELECT 
        c.ContractID,
        MONTH(CURDATE()), YEAR(CURDATE()),
        r.RoomPrice, 0, 3500, 0, 15000,
        r.RoomPrice, 'Chưa thanh toán',
        NOW(), DATE_ADD(NOW(), INTERVAL 5 DAY)
    FROM Contracts c
    JOIN Rooms r ON c.RoomID = r.RoomID
    WHERE c.Status = 'Hiệu lực'
      AND NOT EXISTS (
          SELECT 1 FROM Invoices i 
          WHERE i.ContractID = c.ContractID 
            AND i.Month = MONTH(CURDATE())
            AND i.Year = YEAR(CURDATE())
      )
");

// 🔹 Tự động tính lại TotalAmount nếu chưa có hoặc = 0
$conn->query("
    UPDATE Invoices 
    SET TotalAmount = RoomFee + (ElectricUsage * ElectricPrice) + (WaterUsage * WaterPrice)
    WHERE TotalAmount IS NULL OR TotalAmount = 0
");

// 🔹 Gán hạn thanh toán mặc định nếu còn null hoặc sai định dạng
$conn->query("
    UPDATE Invoices 
    SET DueDate = DATE_ADD(CreatedAt, INTERVAL 5 DAY)
    WHERE DueDate IS NULL
");



// 🔹 Cập nhật trạng thái “Quá hạn” nếu quá hạn mà chưa thanh toán
$conn->query("
    UPDATE Invoices 
    SET Status = 'Quá hạn'
    WHERE Status = 'Chưa thanh toán'
      AND DueDate IS NOT NULL
      AND DueDate < CURDATE()
");


// ==================== 🧭 2️⃣ BỘ LỌC ====================
$status  = $_GET['status'] ?? 'all';
$keyword = $_GET['search'] ?? '';
$month   = $_GET['month'] ?? 'all';

// ==================== 📊 3️⃣ THỐNG KÊ ====================
$statsSql = "
    SELECT 
        SUM(Status = 'Chưa thanh toán') as unpaid,
        SUM(Status = 'Đã thanh toán') as paid,
        SUM(Status = 'Quá hạn') as overdue,
        COUNT(*) as total
    FROM Invoices
";
$stats = $conn->query($statsSql)->fetch_assoc();

$totalCollected = $conn->query("SELECT SUM(TotalAmount) as sum FROM Invoices WHERE Status='Đã thanh toán'")->fetch_assoc()['sum'] ?? 0;
$totalUnpaid = $conn->query("SELECT SUM(TotalAmount) as sum FROM Invoices WHERE Status IN ('Chưa thanh toán','Quá hạn')")->fetch_assoc()['sum'] ?? 0;

// ==================== 🧾 4️⃣ DANH SÁCH HÓA ĐƠN ====================
$sql = "
    SELECT 
        i.InvoiceID, i.Month, i.Year, i.RoomFee, i.TotalAmount, i.Status,
        i.CreatedAt, i.DueDate, i.PaidAt, c.ContractID, 
        s.FullName, s.StudentCode, r.RoomNumber, b.BuildingName
    FROM Invoices i
    JOIN Contracts c ON i.ContractID = c.ContractID
    JOIN Students s ON c.StudentID = s.StudentID
    JOIN Rooms r ON c.RoomID = r.RoomID
    JOIN Buildings b ON r.BuildingID = b.BuildingID
    WHERE 1=1
";

if ($status !== 'all') {
    $s = $conn->real_escape_string($status);
    $sql .= " AND i.Status = '$s'";
}

if (!empty($keyword)) {
    $k = $conn->real_escape_string($keyword);
    $sql .= " AND (s.FullName LIKE '%$k%' OR s.StudentCode LIKE '%$k%' OR r.RoomNumber LIKE '%$k%' OR b.BuildingName LIKE '%$k%')";
}

if (!empty($month) && $month !== 'all') {
    $monthNum = (int)substr($month, 5, 2);
    $yearNum  = (int)substr($month, 0, 4);
    $sql .= " AND i.Month = $monthNum AND i.Year = $yearNum";
}

$sql .= " ORDER BY i.Year DESC, i.Month DESC, i.InvoiceID DESC";
$result = $conn->query($sql);

// ==================== ⚙️ HÀM HỖ TRỢ ====================
function formatMoney($amount)
{
    return number_format($amount, 0, ',', '.') . ' ₫';
}

function getStatusClass($status)
{
    return strtolower(str_replace(' ', '-', $status));
}

function getDaysOverdue($dueDate)
{
    $due = new DateTime($dueDate);
    $now = new DateTime();
    if ($now > $due) {
        return $now->diff($due)->days;
    }
    return 0;
}
?>
<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="<?= htmlspecialchars($csrf, ENT_QUOTES) ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản lý Hóa đơn | Hệ thống Ký túc xá</title>
    <link rel="stylesheet" href="../../../assets/css/admin/admin_header.css">
    <link rel="stylesheet" href="../../../assets/css/staff/invoice/staff_invoice.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>

<body>
    <div class="invoice-container">
        <div class="page-header">
            <h2><i class="fas fa-file-invoice"></i> Quản lý Hóa đơn</h2>
            <form class="search-form" method="get">
                <input type="hidden" name="status" value="<?= htmlspecialchars($status) ?>">
                <input type="hidden" name="month" value="<?= htmlspecialchars($month) ?>">
                <input type="text" name="search" placeholder="Tìm theo tên, MSSV, phòng, tòa nhà..." value="<?= htmlspecialchars($keyword) ?>">
                <button type="submit"><i class="fas fa-search"></i> <span>Tìm kiếm</span></button>
            </form>
        </div>

        <!-- 🔔 Thông báo tự động -->
        <div class="auto-gen-alert">
            <i class="fas fa-robot"></i>
            <div class="content">
                <h4>Hệ thống tự động hóa đơn</h4>
                <p>Hóa đơn được tự động tạo hàng tháng cho hợp đồng hiệu lực và cập nhật trạng thái quá hạn.</p>
            </div>
        </div>

        <!-- 📊 Thống kê -->
        <div class="stats-container">
            <div class="stat-card unpaid">
                <div class="stat-number"><?= $stats['unpaid'] ?? 0 ?></div>
                <div class="stat-label">Chưa thanh toán</div>
            </div>
            <div class="stat-card paid">
                <div class="stat-number"><?= $stats['paid'] ?? 0 ?></div>
                <div class="stat-label">Đã thanh toán</div>
            </div>
            <div class="stat-card overdue">
                <div class="stat-number"><?= $stats['overdue'] ?? 0 ?></div>
                <div class="stat-label">Quá hạn</div>
            </div>
            <div class="stat-card">
                <div class="stat-number" style="color: var(--dark);"><?= $stats['total'] ?? 0 ?></div>
                <div class="stat-label">Tổng hóa đơn</div>
            </div>
            <div class="stat-card collected">
                <div class="stat-number"><?= formatMoney($totalCollected) ?></div>
                <div class="stat-label">Đã thu</div>
            </div>
            <div class="stat-card uncollected">
                <div class="stat-number"><?= formatMoney($totalUnpaid) ?></div>
                <div class="stat-label">Chưa thu</div>
            </div>
        </div>

        <!-- 🧭 Bộ lọc -->
        <form method="get" class="filters">
            <input type="hidden" name="search" value="<?= htmlspecialchars($keyword) ?>">

            <div class="filter-group">
                <label><i class="fas fa-filter"></i> Trạng thái:</label>
                <select name="status" onchange="this.form.submit()">
                    <option value="all" <?= $status == 'all' ? 'selected' : '' ?>>Tất cả trạng thái</option>
                    <option value="Chưa thanh toán" <?= $status == 'Chưa thanh toán' ? 'selected' : '' ?>>⏳ Chưa thanh toán</option>
                    <option value="Đã thanh toán" <?= $status == 'Đã thanh toán' ? 'selected' : '' ?>>✅ Đã thanh toán</option>
                    <option value="Quá hạn" <?= $status == 'Quá hạn' ? 'selected' : '' ?>>⚠️ Quá hạn</option>
                </select>
            </div>

            <div class="filter-group">
                <label><i class="fas fa-calendar-alt"></i> Tháng/Năm:</label>
                <select name="month" onchange="this.form.submit()">
                    <option value="all" <?= $month == 'all' ? 'selected' : '' ?>>Tất cả tháng</option>
                    <?php
                    // 🗓️ Hiển thị 3 năm gần nhất: năm trước, năm hiện tại, năm sau
                    $currentYear = date('Y');
                    for ($y = $currentYear - 2; $y <= $currentYear + 1; $y++) {
                        echo "<optgroup label='Năm $y'>";
                        for ($m = 1; $m <= 12; $m++) {
                            $val = sprintf('%04d-%02d', $y, $m);
                            $label = sprintf('Tháng %d / %d', $m, $y);
                            $selected = ($month == $val) ? 'selected' : '';
                            echo "<option value='$val' $selected>$label</option>";
                        }
                        echo "</optgroup>";
                    }
                    ?>
                </select>
            </div>
        </form>


        <!-- 🧾 Danh sách hóa đơn -->
        <div class="invoice-table">
            <?php if ($result && $result->num_rows > 0): ?>
                <table>
                    <thead>
                        <tr>
                            <th>Mã HĐ</th>
                            <th>Sinh viên</th>
                            <th>Phòng</th>
                            <th>Tổng tiền</th>
                            <th>Trạng thái</th>
                            <th>Tháng/Năm</th>
                            <th>Ngày tạo</th>
                            <th>Hạn thanh toán</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php while ($row = $result->fetch_assoc()):
                            $statusClass = getStatusClass($row['Status']);
                            $amountClass = $row['Status'] === 'Đã thanh toán' ? 'paid' : ($row['Status'] === 'Quá hạn' ? 'overdue' : '');
                            $daysOverdue = $row['Status'] === 'Quá hạn' ? getDaysOverdue($row['DueDate']) : 0;
                        ?>
                            <tr>
                                <td data-label="Mã HĐ">
                                    <strong>#<?= $row['InvoiceID'] ?></strong>
                                </td>
                                <td data-label="Sinh viên">
                                    <div>
                                        <strong><?= htmlspecialchars($row['FullName']) ?></strong>
                                        <br>
                                        <small><?= htmlspecialchars($row['StudentCode']) ?></small>
                                        <br>
                                        <small style="color: var(--gray);"><?= htmlspecialchars($row['BuildingName']) ?></small>
                                    </div>
                                </td>
                                <td data-label="Phòng">
                                    <?= htmlspecialchars($row['RoomNumber']) ?>
                                </td>
                                <td data-label="Tổng tiền" class="amount <?= $amountClass ?>">
                                    <?= formatMoney($row['TotalAmount']) ?>
                                </td>
                                <td data-label="Trạng thái">
                                    <span class="status-badge <?= $statusClass ?>">
                                        <?= htmlspecialchars($row['Status']) ?>
                                        <?php if ($daysOverdue > 0): ?>
                                            <br><small style="color:red;">(Quá hạn <?= $daysOverdue ?> ngày)</small>
                                        <?php endif; ?>
                                    </span>
                                </td>
                                <td data-label="Tháng/Năm">
                                    <?= $row['Month'] ?>/<?= $row['Year'] ?>
                                </td>
                                <td data-label="Ngày tạo">
                                    <?= date('d/m/Y', strtotime($row['CreatedAt'])) ?>
                                </td>
                                <td data-label="Hạn thanh toán">
                                    <?= date('d/m/Y', strtotime($row['DueDate'])) ?>
                                    <?php if ($row['Status'] === 'Đã thanh toán' && !empty($row['PaidAt'])): ?>
                                        <br>
                                        <small style="color: var(--success);">
                                            Đã thanh toán: <?= date('d/m/Y', strtotime($row['PaidAt'])) ?>
                                        </small>
                                    <?php endif; ?>
                                </td>
                                <td data-label="Thao tác">
                                    <div style="display:flex; gap:5px; flex-wrap: wrap;">
                                        <a href="invoice_detail.php?id=<?= $row['InvoiceID'] ?>" class="btn btn-view" title="Xem chi tiết">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <?php if ($_SESSION['Role'] === 'Admin'): ?>
                                            <button class="btn btn-delete" onclick="deleteInvoice(<?= $row['InvoiceID'] ?>, '<?= htmlspecialchars($row['FullName']) ?>')" title="Xóa hóa đơn">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                        <?php endwhile; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <div class="no-data">
                    <i class="fas fa-inbox"></i>
                    <p>Không có hóa đơn nào phù hợp với tiêu chí tìm kiếm.</p>
                    <a href="?status=all&month=all&search=" class="btn btn-view" style="margin-top: 15px;">
                        <i class="fas fa-refresh"></i> Xem tất cả hóa đơn
                    </a>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <script>
        const CSRF_TOKEN = document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '';

        // 🗑️ Xóa hóa đơn
        function deleteInvoice(id, name) {
            Swal.fire({
                title: 'Xác nhận xóa',
                html: `<p>Bạn có chắc muốn xóa hóa đơn của <strong>${name}</strong>?</p><p class="text-muted">Hành động này không thể hoàn tác.</p>`,
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#e63946',
                cancelButtonColor: '#6c757d',
                confirmButtonText: '<i class="fas fa-trash"></i> Xóa',
                cancelButtonText: '<i class="fas fa-times"></i> Hủy',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    const deleteBtn = event.target;
                    const originalHTML = deleteBtn.innerHTML;
                    deleteBtn.innerHTML = '<div class="loading"></div>';
                    deleteBtn.disabled = true;

                    fetch('invoice_delete_api.php', {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded',
                                'Accept': 'application/json',
                                'X-Requested-With': 'XMLHttpRequest'
                            },
                        body: new URLSearchParams({
                            id,
                            _csrf: CSRF_TOKEN
                        })
                    })
                        .then(r => r.json())
                        .then(data => {
                            if (data.status === 'success') {
                                Swal.fire({
                                    icon: 'success',
                                    title: 'Đã xóa!',
                                    text: data.message,
                                    timer: 2000,
                                    showConfirmButton: false
                                });
                                setTimeout(() => location.reload(), 800);
                            } else {
                                Swal.fire('Lỗi!', data.message, 'error');
                                deleteBtn.innerHTML = originalHTML;
                                deleteBtn.disabled = false;
                            }
                        })
                        .catch(() => {
                            Swal.fire('Lỗi!', 'Không thể kết nối đến máy chủ', 'error');
                            deleteBtn.innerHTML = originalHTML;
                            deleteBtn.disabled = false;
                        });
                }
            });
        }

        // Hiển thị thông báo từ session
        <?php if (isset($_SESSION['message'])): ?>
            Swal.fire({
                icon: '<?= $_SESSION['message_type'] ?? 'success' ?>',
                title: '<?= $_SESSION['message'] ?>',
                confirmButtonColor: '#4361ee',
                timer: 3000
            });
            <?php unset($_SESSION['message'], $_SESSION['message_type']); ?>
        <?php endif; ?>
    </script>
</body>

</html>
